main: aliuly\nechest\Main
api: 1.12.0
load: POSTWORLD

name: NetherChests
description: An Ender Chest type plugin
version: 1.1.1
author: aliuly
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/NetherChests

permissions:
